version: '3.8'
services:
  app:
    image: thanhtungo/vku-java-spring-boot:latest
    ports:
      - '8888:8888'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/spring
      SPRING_DATASOURCE_USERNAME: developer
      SPRING_DATASOURCE_PASSWORD: 147258369
    depends_on:
      - db
  db:
    image: mariadb:11.2
    restart: always
    environment:
      MARIADB_DATABASE: spring
      MARIADB_USER: developer
      MARIADB_PASSWORD: 147258369
      MARIADB_ROOT_PASSWORD: root_pass
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
