version: '3.9'
services:
  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root_password
      MARIADB_USER: developer
      MARIADB_PASSWORD: developer_password
      MARIADB_DATABASE: spring
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mariadb
volumes:
  db_data:
