version: '3.8'
services:
  app:
    image: thanhtungo/vku-java-spring-boot:latest
    ports:
      - '8888:8888'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/spring
      SPRING_DATASOURCE_USERNAME: developer
      SPRING_DATASOURCE_PASSWORD: 147258369
      SPRING_DATA_MONGODB_URI: mongodb://root:root_password@mongo:27017/spring
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: redis_password
    depends_on:
      db:
        condition: service_healthy
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy
  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_DATABASE: spring
      MARIADB_USER: developer
      MARIADB_PASSWORD: 147258369
      MARIADB_ROOT_PASSWORD: root_pass
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      timeout: 20s
      retries: 10
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_password
      MONGO_INITDB_DATABASE: spring
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      timeout: 10s
      retries: 10
      interval: 5s
  redis:
    image: redis:7-alpine
    restart: always
    command: redis-server --requirepass redis_password
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      timeout: 3s
      retries: 5
volumes:
  db_data:
  mongo_data:
  redis_data:
