version: '3.8'
services:
  app:
    image: thanhtungo/vku-java-spring-boot:latest
    ports:
      - '8888:8888'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/spring
      SPRING_DATASOURCE_USERNAME: developer
      SPRING_DATASOURCE_PASSWORD: 147258369
      SPRING_DATA_MONGODB_URI: mongodb://root:root_password@mongo:27017/spring
    depends_on:
      - db
      - mongo
  db:
    image: mariadb:latest
    restart: always
    environment:
      MARIADB_DATABASE: spring
      MARIADB_USER: developer
      MARIADB_PASSWORD: 147258369
      MARIADB_ROOT_PASSWORD: root_pass
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_password
      MONGO_INITDB_DATABASE: spring
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
volumes:
  db_data:
  mongo_data:
