version: '3'
services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - '3100:3100'

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3200:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
